[General]
MacroID=4c8dd79e-0281-490b-8cdf-f4e61700986c
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
Description=我录制的脚本1
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 756, 344
MoveTo 616, 258
Delay 1714
LeftDown 1
Delay 3
LeftDown 1
Delay 637
LeftUp 1
Delay 1
LeftUp 1
'==========以上是按键精灵录制的内容==========
